#!/usr/bin/env python

from std_msgs.msg import String
from geometry_msgs.msg import Twist
from datetime import datetime
from turtlesim.srv import Spawn, Kill
import rospy
import time
import pytz



# get current local time
def get_time():
    timezone = pytz.timezone('Asia/Kuala_Lumpur')
    now = datetime.now(timezone)
    return now.hour, now.minute, now.second
    
# moving turtle
def drawone(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=3)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    time.sleep(0.5)
    command.linear.x = 0.6
    command.angular.z = 0.0        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.57        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.57        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0.6
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0   
    rospy.loginfo(command)
    pub.publish(command)
    
def drawtwo(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    time.sleep(0.5)
    
    time.sleep(1.5)
    command.linear.x = 1.3
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.6
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.3
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.6
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.3
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    
def drawthree(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(0.5)
    command.linear.x = 0
    command.angular.z = -3.144       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0.3
    command.angular.z = 0.0        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 3.144       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0.0     
    rospy.loginfo(command)
    pub.publish(command)
    
def drawfour(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(0.5)
    command.linear.x = 0
    command.angular.z = -1.7      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0.0        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.7      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 2
    command.angular.z = 0        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0.7
    command.angular.z = 0        
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.54      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1
    command.angular.z = 0        
    rospy.loginfo(command)
    pub.publish(command)
    
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 2.3
    command.angular.z = 0        
    rospy.loginfo(command)
    pub.publish(command)
    
def drawfive(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 3.144     
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.5
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.4
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
def drawsix(name):

    drawfive(name)
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.7
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
def drawseven(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(1.5)
    command.linear.x = 0.85
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.5
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0.3
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
def drawzero(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574       
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0       
    rospy.loginfo(command)
    pub.publish(command)
    
    
def draweight(name):
    drawzero(name)
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z =-3.144    
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.5
    command.angular.z =0    
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)

def drawnine(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()

    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 3
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -3.144   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.5
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = 1.574   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.2
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 0
    command.angular.z = -1.574   
    rospy.loginfo(command)
    pub.publish(command)
    
    time.sleep(1.5)
    command.linear.x = 1.5
    command.angular.z = 0      
    rospy.loginfo(command)
    pub.publish(command)

# Draw center dots
def drawdot(name):
    cmdPublisher = name + '/cmd_vel'
    pub = rospy.Publisher(cmdPublisher, Twist, queue_size=15)
    rospy.init_node('mynode', anonymous=True)
    rate = rospy.Rate(10)
    command = Twist()

    time.sleep(1.5)
    command.linear.x = 1
    command.angular.z = 6     
    rospy.loginfo(command)
    pub.publish(command)

def draw_time(name,digit):
    digit_funcs = { 0:drawzero,
                    1:drawone,
                    2:drawtwo,
                    3:drawthree,
                    4:drawfour,
                    5:drawfive,
                    6:drawsix,
                    7:drawseven,
                    8:draweight,
                    9:drawnine}
    digit_funcs[digit](name)
    
    
def remove_turtle(name):
    rospy.wait_for_service('/kill')
    kill_service = rospy.ServiceProxy('/kill', Kill)
    kill_service(name)

if __name__ == '__main__':
    hour, minute, second = get_time()
    time.sleep(2)
    
    # get time numbers
    sthour, ndhour = (hour // 10) , (hour % 10)
    stminute, ndminute = (minute // 10),  (minute % 10)
    stsec , ndsec = (second // 10) , (second % 10)

    drawdot("turtle1")
    drawdot("turtle5")

    draw_time("turtle0",sthour)
    draw_time("turtle2",ndhour)
    draw_time("turtle3",stminute)
    draw_time("turtle4",ndminute)
    
    draw_time("turtle6",stsec)
    draw_time("turtle7",ndsec)

    time.sleep(3)
    remove_turtle('turtle0')
    remove_turtle('turtle1')
    remove_turtle('turtle2')
    remove_turtle('turtle3')
    remove_turtle('turtle4')
    remove_turtle('turtle5')
    remove_turtle('turtle6')
    remove_turtle('turtle7')

  

