#!/usr/bin/env python
import rospy
import time
from turtlesim.srv import Spawn, Kill


def spawn_turtle(name, pos_x, pos_y, angle):
    rospy.wait_for_service('spawn')
    try:
        time_turtle = rospy.ServiceProxy('spawn', Spawn) 
        time_turtle(pos_x, pos_y, angle, name)
    except rospy.ServiceException as error:
        print("Error: {}".format(error))
 

if __name__ == '__main__':
        
    # spawn turtles
    spawn_turtle("turtle0",0.65,9,0)
    spawn_turtle("turtle2",3.3,9,0)
    spawn_turtle("turtle3",6.5,9,0)
    spawn_turtle("turtle4",9,9,0)
    
    spawn_turtle("turtle5",5.6,7.5,0)
    
    spawn_turtle("turtle6", 3, 4, 0)
    spawn_turtle("turtle7", 6, 4, 0)
    

